namespace Trion.SDK.Enums
{
    public enum WeaponId : short
    {
        None,
        Deagle = 1,
        Elite,
        Fiveseven,
        Glock,
        Ak47 = 7,
        Aug,
        Awp,
        Famas,
        G3SG1,
        GalilAr = 13,
        M249,
        M4A1 = 16,
        Mac10,
        P90 = 19,
        Mp5sd = 23,
        Ump45,
        Xm1014,
        Bizon,
        Mag7,
        Negev,
        Sawedoff,
        Tec9,
        Taser,
        Hkp2000,
        Mp7,
        Mp9,
        Nova,
        P250,
        Scar20 = 38,
        Sg553,
        Ssg08,
        GoldenKnife,
        Knife_CT = 42,
        Knife_T = 59,
        M4a1_s = 60,
        Usp_s,
        Cz75a = 63,
        Revolver,
        GhostKnife = 80,

        Bayonet = 500,
        CSS = 503,
        Flip = 505,
        Gut,
        Karambit,
        M9Bayonet,
        Huntsman,
        Falchion = 512,
        Bowie = 514,
        Butterfly,
        Daggers,
        Cord,
        Canis,
        Ursus = 519,
        Navaja,
        OutDoor,
        Stiletto = 522,
        Talon,
        Skeleton = 525,

        GloveStuddedBloodhound = 5027,
        GloveT,
        GloveCT,
        GloveSporty,
        GloveSlick,
        GloveLeatherWrap,
        GloveMotorcycle,
        GloveSpecialist,
        GloveHydra
    }
}